### PR TITLE
Rename FTPStream to FtpStream

### PR DESCRIPTION
**Pull request by matt2xu**
This is the smallest change, so that's why I'm starting with this one. We will need to update the crate's version number to account for this breaking change.

### CODE REVIEW

**Comment by matt2xu** [comment]
Hmm I didn't know that there was a CI test. I think it fails because there is no FTP server running there, hence the "Connection refused" error message. Is there a way to have a dummy FTP server configured for testing?

**Comment by mattnenterprise** [comment]
The documentation you added gets run like it is a test. So that is why it is failing for this branch and not the master. I would be nice to be able to setup an FTP server for testing. We might be able to set one up as a docker container, and testing the code that way. If you want I can look at adding an FTP docker container for testing later today?

**Comment by mattnenterprise** [comment]
We might be able to use the following docker image: https://hub.docker.com/r/stilliard/pure-ftpd/

**Comment by matt2xu** [comment]
Why not, it would be ideal actually! In the meantime, maybe we could use a public server? A quick search on Google pointed me to speedtest.tele2.net, which seems to work for this test. Do you want me to update the code with that server to see if it builds? (not sure if outgoing connections are restricted or not on Travis)

**Comment by matt2xu** [comment]
I modified the .travis.yml to install pure-ftp before building and testing the crate, copied from https://github.com/SaltwaterC/ftp-get/blob/master/.travis.yml

It now fails because the crate doesn't handle multi-line relies yet. Would you be ok accepting this pull request as it is, and let me make a new pull request handling multi-line replies later?

**Comment by matt2xu** [comment]
I added support for multiple line replies with a BufReader, which makes the build suceed :smile: For now a BufReader is created at each call to read_response, it works but this is not exactly optimal though ^^

**Comment by mattnenterprise** [comment]
@matt2xu Can you rebase this ? If you don't know how to rebase just let me know. I will help you through it.

**Pull request closed without merging**
