### PR TITLE
implement list

### PR DESCRIPTION
**Pull request by little-dude**
cf: https://github.com/mattnenterprise/rust-ftp/issues/10

This is work in progress. I need to add `nlst` as well. But if you have feedback aleady it's great. Maybe I should rename `list()` to `ls()`, also.

### CODE REVIEW

**Comment by matt2xu** [comment]
It looks fine. The code will be a bit simpler once I take the time to make a pull request for error handling :-)
Also, I don't think you need to explicitly drop the connection, I believe the stream will be automatically dropped when it goes out of scope if I understand correctly.

Suggestion: maybe parse the list that is returned, so you get a Vec<FileDesc> for instance, rather than a String?

**Comment by little-dude** [comment]
thanks for the feedback!

> The code will be a bit simpler once I take the time to make a pull request for error handling

Yes, please! :D 

> I don't think you need to explicitly drop the connection

:+1: 

> maybe parse the list that is returned, so you get a Vec for instance, rather than a String?

:+1:

**Comment by mattnenterprise** [comment]
@little-dude Can you resolve the conflicts.

**Comment by little-dude** [comment]
@mattnenterprise I'll probably wait for https://github.com/mattnenterprise/rust-ftp/pull/21, unless you want to merge this first.

**Comment by mattnenterprise** [comment]
@little-dude #21 has been merged

**Comment by matt2xu** [comment]
@little-dude if you want to see this PR merged, you need to update it so it can be merged. To do that, rebase it on top of upstream/master. I doubt you'll have conflicts, so this should go smoothly :-) Then push your changes (forcefully with the -f option) on your list2 branch.

**Comment by little-dude** [comment]
seems that this has been done already. not need to keep this pr open.

**Pull request closed without merging**
