### PR TITLE
Rename FTPStream, support multiple line replies, add buffered read

### PR DESCRIPTION
**Pull request by matt2xu**
New pull request with all changes in one commit. And also @dbrgn 's commit, I'm not sure why.

### CODE REVIEW

**Comment by dbrgn** [comment]
To get rid of that commit, the following should do:

    git remote add upstream https://github.com/mattnenterprise/rust-ftp
    git fetch upstream
    git rebase upstream/master

You'll probably have to force-push (-f) afterwards to overwrite your current commits.

**Comment by matt2xu** [comment]
Thanks for the tip! I was using Eclipse, and did not realize I could force the push. Done!

**Comment by dbrgn** [comment]
Sorry, I accidentally commented on the commit instead of the diff.

Regarding the number conversion:

> The code uses 3 decimal digits, it is therefore guaranteed to be between 0 and 999. You'd have to be on a 8 bit platform to have a problem representing it with a isize :-) Would you rather have the method return a u32? Or something else?

The thing is that a "malicious" ftp server could crash your client by sending a code too high. Could that be possible? In doubt, I'd probably go with u32.

**Comment by dbrgn** [comment]
PS: I don't really have anything to say here, but in general I'd recommend to split up multiple changes (like the rename and the support for multiple line replies) into separate commits in the future, as that simplifies review and debugging :)

**Comment by matt2xu** [comment]
> Sorry, I accidentally commented on the commit instead of the diff.

No problem :wink:

> PS: I don't really have anything to say here, but in general I'd recommend to split up multiple changes

@dbrgn this is what I originally did, see here: https://github.com/mattnenterprise/rust-ftp/pull/15
I squashed all commits into one per @mattnenterprise's request, I suppose it makes the history easier to read once merged.

> The thing is that a "malicious" ftp server could crash your client by sending a code too high. Could that be possible? In doubt, I'd probably go with u32.

No that cannot happen, since the code only parses the first three characters of the line:
`line[0 .. 3].parse()`. This is consistent with RFC 959, which states:

> An FTP reply consists of a three digit number (transmitted as three alphanumeric characters) followed by some text.

By definition this will produce an unsigned number, hence the u32; it could also be usize. To support multiple line replies, the function will keep reading lines until it finds a line that begins with that exact same code followed by a space, per the spec:

> Thus the format for multi-line replies is that the first line will begin with the exact required reply code, followed immediately by a Hyphen, "-" (also known as Minus), followed by text.  The last line will begin with the same code, followed immediately by Space <SP>, optionally some text, and the Telnet end-of-line code.

Note that the function is a bit more liberal, in the sense that it does not verify that the character following the 3-digit code is a hyphen. This is in line with the Robustness Principle defined by TCP, which I think can apply here: "implementations will follow a general principle of robustness:  be conservative in what you do, be liberal in what you accept from others."

**Comment by dbrgn** [comment]
> I squashed all commits into one per @mattnenterprise's request, I suppose it makes the history easier to read once merged.

Ah, didn't see that. :)

> No that cannot happen, since the code only parses the first three characters of the line: line[0 .. 3].parse()

Ah, then I guess it's fine :) A comment noting that might be a good idea though.

I just wondered why `isize` is used in the first place. The number doesn't have any relation with pointer size. So it might as well be an i16 or an u32.

**Comment by mattnenterprise** [comment]
I am going to go ahead and merge this. 

@matt2xu It is easier to have more specific pull requests. Most projects prefer a specific change in each pull request. This could have been done with the changes made here. For example we could split this pull request into the following pull requests: multi-line replies, the usage example, and changing FTPStream to FtpStream. Keep this in mind in the future :smile:  and thanks for the changes! 

@dbrgn I don't have any reason for why that is an isize. So after I merge this pull request you can make a pull-request for making changes.

**Comment by matt2xu** [comment]
@mattnenterprise thanks for the advice, next time I will do that (separate pull requests) :sunglasses:

**Pull request merged**
